### ISSUE TITLE
can't compile diorite-4.4.0 on Fedora 25

### ISSUE THREAD

**Issue by martinkg** [tiliado/diorite#16]
```
[martin@fc25 SPECS]$ rpmbuild -ba diorite.spec 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.zH2FXi
+ umask 022
+ cd /home/martin/rpmbuild/BUILD
+ cd /home/martin/rpmbuild/BUILD
+ rm -rf diorite-4.4.0
+ /usr/bin/gzip -dc /home/martin/rpmbuild/SOURCES/diorite-4.4.0.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd diorite-4.4.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ rm ./waf
+ rm -rf ./.waf
+ sed -i -e 's|#!/usr/bin/env python3|#!/usr/bin/python3|g' testgen.py
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.JR5em4
+ umask 022
+ cd /home/martin/rpmbuild/BUILD
+ cd diorite-4.4.0
+ waf-3 configure --prefix=/usr --libdir=/usr/lib64 --novaladoc
Setting top to                           : /home/martin/rpmbuild/BUILD/diorite-4.4.0 
Setting out to                           : /home/martin/rpmbuild/BUILD/diorite-4.4.0/build 
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/usr/share/waf3/waflib/Scripting.py", line 121, in waf_entry_point
    run_commands()
  File "/usr/share/waf3/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/usr/share/waf3/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/usr/share/waf3/waflib/Configure.py", line 84, in execute
    super(ConfigurationContext,self).execute()
  File "/usr/share/waf3/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/usr/share/waf3/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/martin/rpmbuild/BUILD/diorite-4.4.0/wscript", line 146, in configure
    add_version_info(ctx)
  File "/home/martin/rpmbuild/BUILD/diorite-4.4.0/wscript", line 61, in add_version_info
    bare_version, n_commits, revision_id = get_git_version()
ValueError: not enough values to unpack (expected 3, got 1)
error: Bad exit status from /var/tmp/rpm-tmp.JR5em4 (%build)
```

only works if i use this patch:

```
[root@fc25 tmp]# cat -v /home/martin/rpmbuild/SOURCES/wscript.patch
--- diorite-4.4.0.orig/wscript	2017-05-27 16:36:46.000000000 +0200
+++ diorite-4.4.0/wscript	2017-05-31 09:05:17.753873846 +0200
@@ -50,11 +50,6 @@
 
 
 def get_git_version():
-	import subprocess
-	try:
-		output = subprocess.Popen(["git", "describe", "--tags", "--long"], stdout=subprocess.PIPE).communicate()[0]
-		return output.decode("utf-8").strip().split("-")
-	except Exception as e:
 		return VERSION, "0", REVISION_SNAPSHOT
 
 def add_version_info(ctx):
```

waf-python3-1.9.11-1.fc25 package with /usr/bin/waf-3 is installed.

**Comment by fenryxo** [comment]
Thanks for reporting the issue. It also occurs in Nuvola. I've fixed both in master branches.
