### ISSUE TITLE
diorite-4.12.0 compilation fails with 'raise StopIteration' on Fedora 29 rawhide

### ISSUE THREAD

**Issue by martinkg** [tiliado/diorite#26]
compilation fails [1] on fedora 29 rawhide

```
+ umask 022
+ cd /builddir/build/BUILD
+ cd diorite-4.12.0
+ waf configure --prefix=/usr --libdir=/usr/lib64 --novaladoc
Traceback (most recent call last):
  File "/usr/share/waf3/waflib/Node.py", line 295, in ant_iter
    raise StopIteration
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/share/waf3/waflib/Scripting.py", line 121, in waf_entry_point
    run_commands()
  File "/usr/share/waf3/waflib/Scripting.py", line 178, in run_commands
    parse_options()
  File "/usr/share/waf3/waflib/Scripting.py", line 151, in parse_options
    Context.create_context('options').execute()
  File "/usr/share/waf3/waflib/Options.py", line 148, in execute
    super(OptionsContext,self).execute()
  File "/usr/share/waf3/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/usr/share/waf3/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/builddir/build/BUILD/diorite-4.12.0/wscript", line 140, in options
    ctx.load('compiler_c vala')
  File "/usr/share/waf3/waflib/Context.py", line 84, in load
    fun(self)
  File "/usr/share/waf3/waflib/Tools/compiler_c.py", line 39, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/usr/share/waf3/waflib/Context.py", line 323, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/usr/share/waf3/waflib/Node.py", line 344, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/usr/share/waf3/waflib/Node.py", line 344, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
error: Bad exit status from /var/tmp/rpm-tmp.1zlcEa (%build)
    Bad exit status from /var/tmp/rpm-tmp.1zlcEa (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/diorite.spec
```

[1] https://kojipkgs.fedoraproject.org//work/tasks/9474/28519474/build.log

**Comment by fenryxo** [comment]
Hello @martinkg. It looks like a WAF bug. Could you check that Diorite builds with the bundled waf? [It does on Fedora 28](https://circleci.com/gh/tiliado/nuvolaruntime/50).

**Comment by martinkg** [comment]
build.log with bundeld waf version on Fedora 29
[1] https://kojipkgs.fedoraproject.org//work/tasks/6771/28536771/build.log

**Comment by martinkg** [comment]
Thomas Moschny maintainer of the fedora waf package told [me](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/MSJMZRMWL7QKJXSHZYCVMZGVQV6ENQSE/)
> 
> I think we need to update system waf, version 2.0.7 improves Python
> 3.7 compatibility."

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/MSJMZRMWL7QKJXSHZYCVMZGVQV6ENQSE/

**Comment by fenryxo** [comment]
Could you try with waf 2.0.9?

```
wget https://waf.io/waf-2.0.9
sed -i 's@#!/usr/bin/env python@#!/usr/bin/env python3@' waf-2.0.9
mv waf-2.0.9 waf
```

If it works, could you send a pull request to both diorite & nuvolaruntime?

**Comment by martinkg** [comment]
ok, compiles until [ 10/135] Linking build/Drtgtk-1.0.typelib
but then fails [with ](https://kojipkgs.fedoraproject.org//work/tasks/9197/28539197/build.log)

```
Drtgtk-1.0.gir:564:1: warning: element property from state 24 is unknown, ignoring
Drtgtk-1.0.gir:572:1: warning: element property from state 24 is unknown, ignoring
Drtgtk-1.0.gir:580:1: warning: element property from state 24 is unknown, ignoring
Drtgtk-1.0.gir:588:1: warning: element property from state 24 is unknown, ignoring
Drtgtk-1.0.gir:596:1: warning: element property from state 24 is unknown, ignoring
Loaded package `/usr/share/vala-0.40/vapi/glib-2.0.vapi'
Loaded package `/usr/share/vala-0.40/vapi/gobject-2.0.vapi'
Loaded package `/usr/share/vala-0.40/vapi/posix.vapi'
Loaded package `/usr/share/vala-0.40/vapi/gio-2.0.vapi'
Loaded package `/usr/share/vala-0.40/vapi/gio-unix-2.0.vapi'
Loaded package `/usr/share/vala-0.40/vapi/gtk+-3.0.vapi'
Loaded package `/usr/share/vala-0.40/vapi/atk.vapi'
Loaded package `/usr/share/vala-0.40/vapi/cairo.vapi'
Loaded package `/usr/share/vala-0.40/vapi/gdk-pixbuf-2.0.vapi'
Loaded package `/usr/share/vala-0.40/vapi/gdk-3.0.vapi'
Loaded package `/usr/share/vala-0.40/vapi/pango.vapi'
Loaded package `/usr/share/vala-0.40/vapi/pangocairo.vapi'
Loaded package `/usr/share/vala-0.40/vapi/x11.vapi'
Loaded package `/usr/share/vala-0.40/vapi/gdk-x11-3.0.vapi'
Loaded package `/builddir/build/BUILD/diorite-4.12.0/build/dioritedb4.vapi'
Loaded package `/usr/share/vala-0.40/vapi/sqlite3.vapi'
Loaded package `/builddir/build/BUILD/diorite-4.12.0/build/dioriteglib4.vapi'
Loaded package `/builddir/build/BUILD/diorite-4.12.0/build/dioritegtk4.vapi'
[ 11/135] Compiling build/dioritetests.vapi
  File "../testgen.py", line 84
    def __init__(self, name, access, parent=None, rtype=None, params=None, throws=None, override=False, abstract=False, anotations=None, async=False):
                                                                                                                                             ^
SyntaxError: invalid syntax
Waf: Leaving directory `/builddir/build/BUILD/diorite-4.12.0/build'
Build failed
```

**Comment by fenryxo** [comment]
That's an unrelated issue - reticketed as tiliado/diorite#27
