### ISSUE TITLE
Release 0.3.1 cannot be compiled

### ISSUE THREAD

**Issue by petRUShka** [tiliado/diorite#8]
File wscript line 31, [upstream](https://github.com/tiliado/diorite/blob/master/wscript#L33):
```
VERSION = "0.3.1+"
```
release [0.3.1](https://github.com/tiliado/diorite/commit/9711602208b728fee8ed2367721f88706009432c):
```
VERSION = "0.3.1"
```

That is causing following error during building package:

```
 File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/wscript", line 201, in configure
    VERSION_SUFFIX = VERSIONS[1]
IndexError: list index out of range
```

**Comment by petRUShka** [comment]
Full log:

```
Setting top to                           : /home/user/AUR/diorite-rolling/src/diorite-0.3.1 
Setting out to                           : /home/user/AUR/diorite-rolling/src/diorite-0.3.1/build 
Version                                  : 0.3.1 
Upstream revision                        : unknown (unsupported build) 
Target platform                          : LINUX 
Install prefix                           : /usr 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'gobject-2.0'               : yes 
Checking for 'gthread-2.0'               : yes 
Checking for program valac-0.8           : not found 
Checking for program valac               : /usr/bin/valac 
Checking for valac version >= (0, 8, 0)  : (0, 34, 4) 
Checking for program valac-0.22          : /usr/bin/valac 
Checking for valac-0.22 version >= (0, 22, 1) : (0, 34, 4) 
Compiler optimizations                        : ON 
Checking for 'glib-2.0' >= 2.40               : yes 
Checking for 'gthread-2.0' >= 2.40            : yes 
Checking for 'gio-2.0' >= 2.40                : yes 
Checking for 'gtk+-3.0' >= 3.10               : yes 
Checking for 'gdk-3.0' >= 3.10                : yes 
Checking for 'gdk-x11-3.0' >= 3.10            : yes 
Checking for 'x11' >= 0                       : yes 
Traceback (most recent call last):
  File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Configure.py", line 128, in execute
    super(ConfigurationContext,self).execute()
  File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Context.py", line 84, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/.waf3-1.7.14-6b92f3c95d8c1bad60826036bf26d63f/waflib/Context.py", line 125, in recurse
    user_function(self)
  File "/home/user/AUR/diorite-rolling/src/diorite-0.3.1/wscript", line 201, in configure
    VERSION_SUFFIX = VERSIONS[1]
IndexError: list index out of range
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by martinkg** [comment]
same issue on Fedora 25 !

**Comment by fenryxo** [comment]
Hello @petRUShka & @martinkg. I apologize for that problem. I should have tested it more carefully. However, 0.3.1 is not a supported release but merely a development snapshot. Please use the latest git master snapshot instead.

**Comment by fenryxo** [comment]
Or you can apply https://github.com/tiliado/diorite/commit/26321c12ece8e67c2365883ff480fb75193161df#diff-dc6134e3d3c869a052520d86f46371dc
